export const GET_COMMENTS_STARTED = 'GET_COMMENTS_STARTED';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAILURE = 'GET_COMMENTS_FAILURE';

export const SET_COMMENTS_STARTED = 'SET_COMMENTS_STARTED';
export const SET_COMMENTS_SUCCESS = 'SET_COMMENTS_SUCCESS';
export const SET_COMMENTS_FAILURE = 'SET_COMMENTS_FAILURE';

export const GET_POST_STARTED = 'GET_POST_STARTED';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAILURE = 'GET_POST_FAILURE';

export const CLEAR_COMMENTS = 'CLEAR_COMMENTS';

export const GET_RELATED_NEWS_STARTED = 'GET_RELATED_NEWS_STARTED';
export const GET_RELATED_NEWS_SUCCESS = 'GET_RELATED_NEWS_SUCCESS';
export const GET_RELATED_NEWS_FAILURE = 'GET_RELATED_NEWS_FAILURE';

export const ADD_NEW_LIKE_STARTED = 'ADD_NEW_LIKE_STARTED';
export const ADD_NEW_LIKE_SUCCESS = 'ADD_NEW_LIKE_SUCCESS';
export const ADD_NEW_LIKE_FAILURE = 'ADD_NEW_LIKE_FAILURE';

export const UP_LIKE = 'UP_LIKE';
