export const TEST = 'TEST';


export const GET_USER_DATA_STARTED = 'GET_USER_DATA_STARTED';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE';

export const SET_INIT_STORE = 'SET_INIT_STORE';
export const SET_MOBILE_NAVIGATE_STATUS = 'SET_MOBILE_NAVIGATE_STATUS';

export const GET_CURRENT_CITY_STARTED = 'GET_CURRENT_CITY_STARTED';
export const GET_CURRENT_CITY_SUCCESS = 'GET_CURRENT_CITY_SUCCESS';
export const GET_CURRENT_CITY_FAILURE = 'GET_CURRENT_CITY_FAILURE';

export const SET_CURRENT_MOVIE = 'SET_CURRENT_MOVIE';

export const GET_SUBSCRIBERS_STARTED = 'GET_SUBSCRIBERS_STARTED';
export const GET_SUBSCRIBERS_SUCCESS = 'GET_SUBSCRIBERS_SUCCESS';
export const GET_SUBSCRIBERS_FAILURE = 'GET_SUBSCRIBERS_FAILURE';

export const GET_TAGS_STARTED = 'GET_TAGS_STARTED';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export const GET_TAGS_FAILURE = 'GET_TAGS_FAILURE';

export const GET_CATEGORIES_STARTED = 'GET_CATEGORIES_STARTED';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

export const GET_POSTS_STARTED = 'GET_POSTS_STARTED';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILURE = 'GET_POSTS_FAILURE';

export const SET_LOGIN_STARTED = 'SET_LOGIN_STARTED';
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS';
export const SET_LOGIN_FAILURE = 'SET_LOGIN_FAILURE';

export const GET_PREVIEW_MAIN_NEWS_STARTED = 'GET_PREVIEW_MAIN_NEWS_STARTED';
export const GET_PREVIEW_MAIN_NEWS_SUCCESS = 'GET_PREVIEW_MAIN_NEWS_SUCCESS';
export const GET_PREVIEW_MAIN_NEWS_FAILURE = 'GET_PREVIEW_MAIN_NEWS_FAILURE';

export const GET_NAVIGATION_CATEGORIES_STARTED = 'GET_NAVIGATION_CATEGORIES_STARTED';
export const GET_NAVIGATION_CATEGORIES_SUCCESS = 'GET_NAVIGATION_CATEGORIES_SUCCESS';
export const GET_NAVIGATION_CATEGORIES_FAILURE = 'GET_NAVIGATION_CATEGORIES_FAILURE';

export const GET_CATEGORIES_NEWS_STARTED = 'GET_CATEGORIES_NEWS_STARTED';
export const GET_CATEGORIES_NEWS_SUCCESS = 'GET_CATEGORIES_NEWS_SUCCESS';
export const GET_CATEGORIES_NEWS_FAILURE = 'GET_CATEGORIES_NEWS_FAILURE';

export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS';
export const SET_THEME_MODE_STATUS = 'SET_THEME_MODE_STATUS';
export const SET_MAIN_CATEGORY = 'SET_MAIN_CATEGORY';

export const GET_PAGINATE_CATEGORIES_NEWS_STARTED = 'GET_PAGINATE_CATEGORIES_NEWS_STARTED';
export const GET_PAGINATE_CATEGORIES_NEWS_SUCCESS = 'GET_PAGINATE_CATEGORIES_NEWS_SUCCESS';
export const GET_PAGINATE_CATEGORIES_NEWS_FAILURE = 'GET_PAGINATE_CATEGORIES_NEWS_FAILURE';

export const GET_MOST_POPULAR_NEWS_STARTED = 'GET_MOST_POPULAR_NEWS_STARTED';
export const GET_MOST_POPULAR_NEWS_SUCCESS = 'GET_MOST_POPULAR_NEWS_SUCCESS';
export const GET_MOST_POPULAR_NEWS_FAILURE = 'GET_MOST_POPULAR_NEWS_FAILURE';

export const GET_MOST_VIEWED_NEWS_STARTED = 'GET_MOST_VIEWED_NEWS_STARTED';
export const GET_MOST_VIEWED_NEWS_SUCCESS = 'GET_MOST_VIEWED_NEWS_SUCCESS';
export const GET_MOST_VIEWED_NEWS_FAILURE = 'GET_MOST_VIEWED_NEWS_FAILURE';

export const GET_MOVIES_STARTED = 'GET_MOVIES_STARTED';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE';

export const GET_SHORT_NEWS_STARTED = 'GET_SHORT_NEWS_STARTED';
export const GET_SHORT_NEWS_SUCCESS = 'GET_SHORT_NEWS_SUCCESS';
export const GET_SHORT_NEWS_FAILURE = 'GET_SHORT_NEWS_FAILURE';

export const SET_CURRENT_LANG = 'SET_CURRENT_LANG';

export const GET_CRYPTO_STARTED = 'GET_CRYPTO_STARTED';
export const GET_CRYPTO_SUCCESS = 'GET_CRYPTO_SUCCESS';
export const GET_CRYPTO_FAILURE = 'GET_CRYPTO_FAILURE';

export const SORT_CRYPTO = 'SORT_CRYPTO';

export const GET_VOTE_STARTED = 'GET_VOTE_STARTED';
export const GET_VOTE_SUCCESS = 'GET_VOTE_SUCCESS';
export const GET_VOTE_FAILURE = 'GET_VOTE_FAILURE';

export const SET_VOTE_STARTED = 'SET_VOTE_STARTED';
export const SET_VOTE_SUCCESS = 'SET_VOTE_SUCCESS';
export const SET_VOTE_FAILURE = 'SET_VOTE_FAILURE';

export const BASE_LOG_STARTED = 'BASE_LOG_STARTED';
export const BASE_LOG_SUCCESS = 'BASE_LOG_SUCCESS';
export const BASE_LOG_FAILURE = 'BASE_LOG_FAILURE';

export const BASE_REG_STARTED = 'BASE_REG_STARTED';
export const BASE_REG_SUCCESS = 'BASE_REG_SUCCESS';
export const BASE_REG_FAILURE = 'BASE_REG_FAILURE';

export const SET_MAGIC_TOKEN = 'SET_MAGIC_TOKEN';
export const SET_MAGIC_NAME = 'SET_MAGIC_NAME';

export const GET_CABINET_LINK_STARTED = 'GET_CABINET_LINK_STARTED';
export const GET_CABINET_LINK_SUCCESS = 'GET_CABINET_LINK_SUCCESS';
export const GET_CABINET_LINK_FAILURE = 'GET_CABINET_LINK_FAILURE';

export const SET_AD_STARTED = 'SET_AD_STARTED';
export const SET_AD_SUCCESS = 'SET_AD_SUCCESS';
export const SET_AD_FAILURE = 'SET_AD_FAILURE';

export const GET_VOTE_RESULT_STARTED = 'GET_VOTE_RESULT_STARTED';
export const GET_VOTE_RESULT_SUCCESS = 'GET_VOTE_RESULT_SUCCESS';
export const GET_VOTE_RESULT_FAILURE = 'GET_VOTE_RESULT_FAILURE';

export const SET_VOTE_RESULT_ALL = 'SET_VOTE_RESULT_ALL';

