export const api = {
  // host:  process.env.REACT_APP_API_URL,
  host: "https://api.magic-rank.com/",
  autHost: "http://api.magic-dao.alphadevteam.com/",
  main: {
    subscribers: "api/v1/social/subscribe",
    tags: "api/v1/tags",
    categories: "api/v1/post-categories",
    posts: "api/v1/posts",
    paginatePosts: "api/v1/posts/pagination",
    login: "api/v1/login/wallet",
    previewMainNews: "api/v1/posts/preview/main",
    crypto: "api/v1/currencies",
    questions: "api/v1/questions",
    questionsResult: "api/v1/questions/stats",
    vote: "api/v1/questions/vote",
    baseLog: "api/v1/login",
    baseReg: "api/v1/register",
    user: "api/v1/user",
    cabinetLink: "api/v1/create-one-time-token",
    ad: "api/v1/ad",
    rank: "api/v1/ratings",
    idoPaginated: "api/v1/ido/paginated",
    idoId: "api/v1/ido",
  },
  post: {
    comments: "api/v1/comments",
    post: "api/v1/posts",
  },
};
